name: Linting and auditing

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master

  detect-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      # - name: trufflehog-actions-scan
      #   uses: edplato/trufflehog-actions-scan@master
      #   with:
      #     scanArguments: '--regex --entropy=False --max_depth=5 --rules /regexes.json' # Add custom options here*
      #     ignore_paths: ./zsh/zshrc

      # - name: detect secrets
      #   uses: edplato/trufflehog-actions-scan@v0.9l-beta
